### ISSUE TITLE
Two keys issue. GPG Keyring has too many secret keys! 

### ISSUE THREAD

**Issue by qunabu** [liip/wrench#18]
Can you help me how to resolve following issue, regarding two keys 

* passbolt healthcheck `sudo su -s /bin/bash -c "./bin/cake passbolt healthcheck" www-data` gives no errors, everything passes ` No error found. Nice one sparky!`
* `gpg --list-secret-keys` on my server list one key 
* `su -s /bin/bash -c "gpg --list-secret-keys" www-data` on my server list one key, the same 

On my machine `gpg --list-secret-keys` lists nothing. 
Calling `wrench diagnose` returns with two errors 

```
[KO] User secret key exists: only one secret key should exist, found 2
[KO] Encryption/decryption using user key (passphrase dialog should open): unable to decrypt data (decryption failed)
``` 

when trying to call eg `wrench add` command i have more details 

```
Traceback (most recent call last):
...
requests_gpgauthlib.exceptions.GPGAuthTooManySecretKeysError: ('GPG Keyring has too many secret keys! You need to specify which one to use!', ['XXX', 'YYY'])
```

What i have tried already 
* removing whole config of wrench `rm -rf ~/.config/wrench/` and importing the key again 

Question is 
* why this is happening ? 
* how to specify which key to use ?
* how to remove keys and use only one ?

**Comment by sephii** [comment]
Wrench stores the key in a separate GPG homedir, which is why `gpg --list-secret-keys` doesn't list your key. To see which keys are available to wrench, run the following command (on your computer, not on the server): `gpg --list-secret-keys --homedir ~/.config/requests_gpgauthlib/.gnupg`.

At the moment there is no way to specify which key id to use, so you'll have to remove the one you're not using. Support for multiple keys is a feature that I'd like to add in the near future though.

**Comment by qunabu** [comment]
@sephii that worked, removing keys from `~/.config/requests_gpgauthlib/` and importing them again. 

My last error is 
```
[KO] Encryption/decryption using user key (passphrase dialog should open): unable to decrypt data (decryption failed)
```
```
requests_gpgauthlib.exceptions.GPGAuthStage1Exception: ('Auth token decryption failed: %s', 'decryption failed')
```

**Comment by qunabu** [comment]
How to resolve last issue is fully described in the readme. Closing this since it is resolved.
